services:  
  # uncomment this when data is ready to pull with the maps
  # web:
  #   build: .
  #   ports:
  #     - "80:8000"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   command: ["python", "app.py"]
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - 5432:5432
    container_name: bathroom-locator
 
volumes:
  pgdata: