services:  
  # uncomment this when data is ready to pull with the maps
  # web:
  #   build: .
  #   ports:
  #     - "80:8000"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   command: ["python", "app.py"]
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/1.create_schema.sql
      - ./sql/insert_data.sql:/docker-entrypoint-initdb.d/2.insert_data.sql
    ports:
      - 5432:5432
    container_name: bathroom-locator
 